### PR TITLE
Adds contenttypegroups creation and assignment/unassignment

### LINKED ISSUE #7: Create ContentTypeGroups when importing ContentTypes

### PR DESCRIPTION
**Pull request by htollefsen**
Aims to resolve #7.

### CODE REVIEW

**Comment by htollefsen** [comment]
@valisj Could you allow spaces before closure parameters (see [scrutinizer inspection](https://scrutinizer-ci.com/g/transfer-framework/ezplatform/inspections/b2108739-2b20-4525-a1af-e002b7a20bf8/patches)) as this is default by PHP-CS-Fixer?

**Comment by ghost** [comment]
@htollefsen The patches should disappear in the next inspection.

**Comment by ghost** [comment]
@htollefsen I've been noticing you added some new classes: `ContentTypeRepository` and `FieldDefinitionRepository`. All they do is map data from our own data structure to eZ Publish structs. Would it be better naming these as `ContentTypeMapper` and `FieldDefinitionMapper` or something similar to that?

**Comment by htollefsen** [comment]
Initially I had bigger plans for the repository classes, but those plans stranded. I agree they should be renamed. PR incoming.

**Pull request merged**
