### PR TITLE
[WIP] Improve compatibility with older kernel versions

### PR DESCRIPTION
**Pull request by ghost**
Addresses #20

### CODE REVIEW

**Comment by htollefsen** [comment]
:+1:  Thanks. Great!
Should we create a separate branch for 5.x support? With slight different composer and travis support? I don't see legacy being supported by php7 any time soon, because of the Null-classes (since it hasn't been renamed in the legacy branch yet, seems it won't be).

**Comment by ghost** [comment]
I had tried changing the `.travis.yml` file so that Travis CI tests different ezpublish-kernel versions, although I wasn't able to get it working. I'll try some other options I have in mind.

**Comment by valisj** [comment]
@htollefsen I'll have to close this issue because I'm not entirely sure how we're going to allow `v2014.11.*` version, when semantically it's larger than `v6.0`. 

See here: http://semver.mwl.be/#?package=ezsystems%2Fezpublish-kernel&version=v2014.11.8&minimum-stability=stable 

This means that when given a chose between `v2014.11.*` and `v6.0`, composer will choose `v2014.11.*` as this is larger than `v6.0`

So I think we'll leave the composer.json file as it is for now. If problems arise, we can always see if we can make another branch for this (although I'm not a fan of this option).

Any thoughts before I close this?

**Comment by ghost** [comment]
@htollefsen I'll have to close this issue because I'm not entirely sure how we're going to allow `v2014.11.*` version, when semantically it's larger than `v6.0`. 

See here: http://semver.mwl.be/#?package=ezsystems%2Fezpublish-kernel&version=v2014.11.8&minimum-stability=stable 

This means that when given a choice between `v2014.11.*` and `v6.0`, composer will choose `v2014.11.*` as this is larger than `v6.0`

So I think we'll leave the composer.json file as it is for now. If problems arise, we can always look at creating another branch for this (although I'm not a fan of this option).

Any thoughts before I close this?

**Comment by htollefsen** [comment]
> This means that when given a choice between v2014.11.\* and v6.0, composer will choose v2014.11.\* as this is larger than v6.0

That's a shame really. No further thoughts.

**Pull request closed without merging**
